### ISSUE TITLE
Hiding the color in the toolbar

### ISSUE THREAD

**Issue by JackWink** [oscardelben/Color-Picker-Pro#1]
Hey, love the tool so far, it makes life a ton simpler.

Only complaint is that the small box showing the color gets a bit distracting when browsing.  It'd be nice to be able to disable the box, leaving the color picker icon for easy access when needed.

**Comment by oscardelben** [comment]
There is a user preference for that. Just click cmd + , to show the preferences or just use the menu.

**Comment by JackWink** [comment]
Ah, my bad.  Preferences didn't show up until I quit, and restarted it.  Thanks for the quick response!
