### ISSUE TITLE
Pixel perfect movement keyboard shortcuts

### ISSUE THREAD

**Issue by lerouxb** [oscardelben/Color-Picker-Pro#12]
It could be nice if you can move the cursor one pixel at a time because right now it can be difficult to pick one pixel when it is surrounded by antialiased colours.

Or what if you want to pick a border colour? I find it difficult to move the mouse cursor just one pixel so I often end up _just_ inside or just outside a border.

(Or maybe that's a job for a different app?)

**Comment by oscardelben** [comment]
That's a good idea. Perhaps by using the arrow keys one could adjust the pixel location. I'm going to add support for this next week when I'll be on town again.

**Comment by skojin** [comment]
I want this feature too, Pixie.app do that

**Comment by oscardelben** [comment]
Done. Pushing an update today.
