### ISSUE TITLE
The crosshairs in the magnified view sit between pixels

### ISSUE THREAD

**Issue by lerouxb** [oscardelben/Color-Picker-Pro#14]
The crosshairs in the magnified view sit to the top and left of the pixel you're selecting. Shouldn't it rather be in the middle of the pixel you're on?

**Comment by oscardelben** [comment]
Hi, sorry for being late on this, could you elaborate a bit on the issue?

**Comment by lerouxb** [comment]
See this screenshot: http://cl.ly/1705443q0P370446291y

The crosshairs sit between four pixels - the four dots that make up the dot on the i including the antialiasing. The pixel to the right and below where the crosshair lines cross is the one that's currently "selected".

It is just a minor cosmetic/usability issue. Was wondering if it would be easy to fix. Each pixel shows up as multiple pixels when zoomed in, so you should be able to just always add one to the x and y so that the crosshair actually crosses the selected pixel. I think. ;)

**Comment by oscardelben** [comment]
Hi, I pushed a commit that should solve this problem. Pushing an upgrade soon.

**Comment by oscardelben** [comment]
Oh, my bad, that actually didn't solve it. Not sure there's an easy fix though.
