### ISSUE TITLE
Provide a way to hide the colorpicker icon from the dock and cmd-tab switching

### ISSUE THREAD

**Issue by lerouxb** [oscardelben/Color-Picker-Pro#15]
Usually apps that sit in the menubar (like dropbox or cloud app) don't have to live in the dock and they don't show up when cmd-tabbing between apps. It would be nice if there was a setting in preferences to hide it. A keyboard shortcut to activate it would probably be enough.

**Comment by oscardelben** [comment]
Unfortunately I can only choose either behavior. One thing you could do if you feel like would be to set the Application is agent property in the info.plist file to YES and recompile the app.
