### ISSUE TITLE
cursor is in the way

### ISSUE THREAD

**Issue by afraser** [oscardelben/Color-Picker-Pro#18]
I just installed on OSX 10.8 and I'm seeing the cursor in color picker pro loupe so the only color that can ever be picked is black on the cursor.

**Comment by oscardelben** [comment]
That's weird, I'll try to reproduce. Sorry about that.

**Comment by afraser** [comment]
I just went to send you a screenshot and it looks like a recent restart fixed it. This is a pretty new machine and I had just installed a bunch of different applications so any number of things could have been interfering. Will let you know if I encounter it again, but I wouldn't waste any more time on it. Thanks for your reply, and for this great tool!

**Comment by oscardelben** [comment]
Np, there may have been some delay issues, let me know if it happens again.
