### ISSUE TITLE
constant crash on mac mini, snow leopard

### ISSUE THREAD

**Issue by ghost** [oscardelben/Color-Picker-Pro#2]
crash report : http://pastebin.com/pJBcSmDY

**Comment by oscardelben** [comment]
Thanks, will take a look and release an update through the app once fixed.

**Comment by oscardelben** [comment]
Actually, does it crash as soon as you launch the app?

**Comment by ghost** [comment]
I should've noticed this earlier, it crashes a few seconds after moving my mouse onto my secondary monitor. If I keep to the primary monitor it's fine.

**Comment by oscardelben** [comment]
I think there are some issues with detecting the second monitor. Do you have any particular setup that you can think of? I've tested it with two monitors and it worked fine, but there may be something I've missed.

I've uploaded a test version where if I can't detect the second monitor for some reason I'll use the default one: http://fructivity.s3.amazonaws.com/ColorPickerPro/TestVersion.zip

If that doesn't work and you're comfortable with Xcode I could send you a version with some logs to help me figure it out.

**Comment by ghost** [comment]
nothing that unusual, the secondary monitor is a different resolution to the primary.

**Comment by ezkl** [comment]
I have the same issue on a MacBook Pro running 10.6.8 with 3 monitors. I'm using a DisplayLink USB adapter for the 2nd and 3rd monitor. As soon as I move my mouse into either of the DisplayLink monitors, the application crashes.

**Comment by oscardelben** [comment]
Hi guys, I'm attaching a test version which logs something to Console.app

If you could make the application crash and then post me what you see in Console.app regarding Color Picker Pro that would help me a lot!

Here's the test version: http://fructivity.s3.amazonaws.com/ColorPickerPro/TestVersion.zip

**Comment by ezkl** [comment]
I've posted a crash log in [this gist](https://gist.github.com/1217953). It seems like this version doesn't crash as quickly as the previous version. I hope the logs help.

**Comment by oscardelben** [comment]
Hi guys, this version should work: http://fructivity.s3.amazonaws.com/ColorPickerPro/Test2.zip

Please let me know if it does and I'll issue an update for everyone.

**Comment by ezkl** [comment]
Working well for me!
