### ISSUE TITLE
The keyboard shortcut to copy color is wrong when the keyboard layout differs from qwerty

### ISSUE THREAD

**Issue by bpierre** [oscardelben/Color-Picker-Pro#3]
Hi,

First, I would like to thank you for this useful tool!

My keyboard layout is [Bépo](http://bepo.fr/wiki/Accueil).

When I hit Command + Maj + P, nothing happens.

If I hit Command + Maj + J (J with Bépo = P with Qwerty), the copy works fine.

So I think the key is hardcoded. Could you change it to consider the keyboard layout?

Thanks!

**Comment by oscardelben** [comment]
Hi bpierre. Yes the j=key is hardcoded, I'll see if I can come up with a more general solution. I'll probably add a preference for choosing the key in the preferences.

**Comment by oscardelben** [comment]
I've added support for this (along with the ability to change the hotkey in the preferences). Look for an update in the coming days!

**Comment by bpierre** [comment]
Nice, thanks!
