### ISSUE TITLE
Feature request - Setting to copy HEX without #

### ISSUE THREAD

**Issue by bryankennedy** [oscardelben/Color-Picker-Pro#4]
Nice looking application. I love the utility of the color clipboard history.

One of the main reasons I open a color picker is to detect a color so that I can paste it into Illustrator, Photoshop, or sometimes the OSX system color picker. These input areas don't allow the # at the beginning of the HEX code. This forces me to copy the color, paste it into some text editor, remove the hash, recopy, then paste into the app I need. I suspect I'm not the only one who's run into this pinch point before.

Adding a little checkbox that would optionally turn off the # before the hexcode would set this application apart from all the other color pickers out there.

I'd offer to look at the code myself, but I have no Obj-C experience. Any thoughts on adding this?

**Comment by oscardelben** [comment]
I'm going to add this option in the next few days.

**Comment by bryankennedy** [comment]
Heck yes, fist pump.

**Comment by oscardelben** [comment]
Added support. Look for an update soon
