### ISSUE TITLE
Color picker mag window stretches pixels at screen boundry

### ISSUE THREAD

**Issue by bryankennedy** [oscardelben/Color-Picker-Pro#5]
This is totally a minor bug, but I thought I would mention it since I noticed.

If you open the color picker and move your cursor to the boundary of the screen the magnifier window runs out of pixels to display in its square box. To compensate the image starts stretching in the direction you are mousing, showing half the pixels by stretching them out. I don't think this affects the ability to pick colors or anything. OSX's Digital Color Meter handles this by filing half the box with an unmouseable black area.

Cheers

**Comment by oscardelben** [comment]
Hi, Yes that's something I knew of, but didn't handle yet. I'll take care of that in a future update. Thanks!

**Comment by oscardelben** [comment]
It's better now. It may have been an update to the underlaying framework but I don't see this problem anymore. Closing for now.
